server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: UserServices
          uri: lb://user-service
          predicates:
            - Path=/v1/apis/users/auth/**,/v1/apis/auth/**