server:
  port: 8080

spring:
  data:
    redis:
      host: redis-19024.c212.ap-south-1-1.ec2.cloud.redislabs.com
      port: 19024
      username: default
      password: yxb57KLsAjSkIfA8ww5KxAp7Ms2ApKev
      ssl:
        enabled: true
  cloud:
    gateway:
      routes:
        - id: UserServices
          uri: lb://user-service
          predicates:
            - Path=/v1/user/apis/**

        - id: video-upload-service
          uri: lb://video-upload-service
          predicates:
            - Path=/v1/upload/**
